from .FedAvg import FedAvg
from .qFFL import qFFL
from .FedMGDA import FedMGDA
from .FedFV import FedFV
from .PropFair import PropFair
from .AFL import AFL
from .AFLeg import AFLeg
from .Tche import Tche
from .STche import STche
from .AFL_new import AFL_new
from .AFLeg_new import AFLeg_new
from .ExcessMTL import ExcessMTL
from .AdaExcessMTL import AdaExcessMTL
from .EPO import EPO
from .FERERO import FERERO